### ISSUE TITLE
Crash with very large passwords

### ISSUE THREAD

**Issue by asymmetric** [mssun/passforios#101] opened 2017-06-22 10:27 UTC
Version: 0.2.7 (App Store)
iOS 10.3.2

The app crashes when displaying a password that is actually a tarsnap encryption file, 69 lines long. Looks like a long piece of text basically.

**Comment by yishilin14** [comment] 2017-07-27 12:47
Sorry for the late reply. I just added a password file with a single line of 8000 "a"s. It seems like everything looks fine.

**Comment by yishilin14** [comment] 2017-08-12 05:08
We are closing this issues because we are not able to reproduce the issue. If you still find this issue in the latest version, please send us a raw text that will crash the app to `developer@passforios.mssun.me` and we will reopen this issue. Thank you. :-)

**Closed by yishilin14** 2017-08-12 05:08 UTC
