### ISSUE TITLE
Prompt repeated when using SSH key

### ISSUE THREAD

**Issue by CyrusRoshan** [mssun/passforios#243] opened 2019-01-20 22:50 UTC
Using MacOS Mojave 10.14.2.

I'm generating keys with `ssh-keygen -m PEM -t rsa -b 2048 -C "user@example.com"`.

Then I'm sending them to my iPhone, and setting up the Git Server with ssh. When entering my password, however, the app repeatedly prompts me for the password after clicking "OK". The input prompt seems to complete, and then immediately comes back.

<img src="https://user-images.githubusercontent.com/8443502/51446118-30910b80-1cd3-11e9-8a23-ee24ead166dd.PNG" alt="screenshot" width="200">

If I give an incorrect password, however, the error dialog comes up and gives me the correct error.

**Comment by yishilin14** [comment] 2019-05-19 18:31
I finally figured out why passforios prompt repeatedly for ssh passphrase after reading https://github.com/libgit2/objective-git/issues/612. When there is an authentification failure, ObjectiveGit expects a "second" credential. Pass has only one credential at hand, the SSH private key. Thus, the only credential will be provide repeatedly...

43ff63e01de22d432c89025674baaea8b04e4f95 fixes this. Pass will now provide the SSH private key just once. If the autentification failed, the cloning step fails. Hopefully it is less confusing now.

**Comment by mssun** [comment] 2019-07-16 06:14
I'm closing this issue since we have released a new version in App Store. Feel free to reopen it if you believe the issue is still valid.

**Closed by mssun** 2019-07-16 06:14 UTC
Labels: in TestFlight
