### ISSUE TITLE
iPad settings window bug

### ISSUE THREAD

**Issue by w2ak** [mssun/passforios#188] opened 2018-05-28 02:51 UTC
Hello :smiley: I hope I gave enough information, please tell me if you need anything else!

And thank you so much for your great work with the app :+1: 

## System information

App version: 0.4.0
iOS version: 11.3
Device: iPad pro

## Bug description

Here are three situations with screenshots. Two of them are buggy.

### First bug

In Pass, open settings. The standard layout is two columns.

![img_0382](https://user-images.githubusercontent.com/12606137/40594821-5f5ee9d6-626c-11e8-9f24-4ccaaacde8ba.jpg)

Then, open the "General" category for example.
**Bug is:** instead of opening in the right column, the general category **also** opens in the left column and there is no way of going back to the list of categories, i.e., the main "Settings" menu.

![img_0383](https://user-images.githubusercontent.com/12606137/40594862-8d2aa26a-626c-11e8-8bae-7d7dcb61daf6.jpg)

### One correct situation

I **stopped** Pass then reopened it but in dual-app mode so that the screen space is smaller and it doesn't use two columns.

![img_0384](https://user-images.githubusercontent.com/12606137/40594905-b8ca2c06-626c-11e8-97b3-8270b1fc1213.jpg)

This time, when I open the "General" category, it obviously opens in the same only column **but** there is as expected the button to go back.

![img_0385](https://user-images.githubusercontent.com/12606137/40594923-d3f51626-626c-11e8-9763-e1d019784ced.jpg)

### Another manifestation of those bugs

So I thought, it doesn't work when there are two columns but works when there is only one. I opened the two columns settings, put it in the buggy situation.

![img_0386](https://user-images.githubusercontent.com/12606137/40594946-fb840184-626c-11e8-981b-ec85e930dcec.PNG)

Then I switched to dual-app mode because I thought since it works with only one column, the button to go back is going to appear. Sadly, it doesn't.

![img_0387](https://user-images.githubusercontent.com/12606137/40594974-18a88802-626d-11e8-9bb6-4cdd1d932387.jpg)

**Comment by jaydisc** [comment] 2018-09-19 04:51
FYI, this is still present in 0.5.1(3).

**Comment by mssun** [comment] 2019-07-16 06:30
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-07-13 at 15 43 13](https://user-images.githubusercontent.com/1270392/61271070-70075480-a758-11e9-93d1-413dbe8e0bd9.png)

**Comment by mssun** [comment] 2019-07-16 06:30
This should be fixed in the latest release. Feel free to reopen if you think the issue is still valid.

**Closed by mssun** 2019-07-16 06:30 UTC
