### ISSUE TITLE
iOS 12 Password Autofill

### ISSUE THREAD

**Issue by eligundry** [mssun/passforios#217] opened 2018-09-18 12:04 UTC
It appears that iOS 12 provides a native autofill API that 3rd party apps can hook into. I’m not an iOS dev, so I couldn’t find the docs on it, but here is a Tweet from 1Password showing their integration with it.

https://twitter.com/1password/status/1041776766120013825?s=21

It would be cool if this app supported this, as it supports the legacy 1Password integration.

**Comment by yishilin14** [comment] 2018-09-18 12:07
I just upgraded to iOS 12 today. We are working on it. Cheers. 

This is a duplicate of #196. I am closing this one and keep that one open. Stay tuned!

**Closed by yishilin14** 2018-09-18 12:07 UTC
