### ISSUE TITLE
Password Autofill

### ISSUE THREAD

**Issue by LevitatingOrange** [mssun/passforios#220] opened 2018-09-21 00:19 UTC
In iOS12 we can now interface with the OS's internal password autofill features via an [API](https://developer.apple.com/documentation/authenticationservices). This would be a great enhancement and could seriously improve the usability of passforios.

**Comment by yishilin14** [comment] 2018-09-21 01:57
Duplicate of #196 . We will implement it this weekend.

**Closed by yishilin14** 2018-09-21 01:57 UTC
