### ISSUE TITLE
ed25519 ssh keys do not work

### ISSUE THREAD

**Issue by jmpolom** [mssun/passforios#305] opened 2019-09-16 19:42 UTC
It appears that ed25519 ssh keys do not work?

I tried loading an ed25519 ssh key and I get an error. "Failed to fetch from remote. Underlying Error: Failed to authenticate SSH session: Unable to extract public key from private key."

Pass for iOS 0.7.0

This was previously reported in #205 but I wanted to create a separate issue since it seemed like this was supposed to have been fixed with the switch to GopenPGP.

**Comment by mssun** [comment] 2019-09-19 18:22
Hi @jmpolom. Thanks for your report.

The SSH channel is established within Git remote operations. Therefore, the SSH key exchange algorithm is not in the PGP library, but in the [objective-git](https://github.com/libgit2/objective-git) library. The issue you were referring is about the PGP library.

So, this is another troublesome issue for a long time caused by our upstream library (objective-git). I think the support of ED25519 ssh key can be solve by updating the `libgit2` library in the `objective-git` library. There are several related issues:

  - https://github.com/libgit2/objective-git/issues/693
  - https://github.com/libgit2/objective-git/issues/692

Similar with our previous PGP library, I'm thinking some alternatives (which should be more reliably and full functional).

**Comment by mssun** [comment] 2019-11-20 08:01
Finally, I managed to update `openssl` (1.1.1d), `libssh2` (1.9.0), `libgit2`(0.28.3) in my forked `objective-git`: https://github.com/mssun/objective-git/commit/4c7b5d196632c7bfaefd6f676ed5480e6e191cca. Pass has been updated in this commit 81eb4b8641616ff5543e037a30a90f1c3e0d2979

Now, these dependencies are in the latest release. This means that ED25519 works now!

I don't have a full list of supported key algorithms, but supported algorithms can be checked in this file:
https://github.com/libssh2/libssh2/blob/libssh2-1.9.0/src/hostkey.c

CI is still working to compile a new release (https://travis-ci.org/mssun/passforios/builds/614401033). Once it's done, we can roll out a TestFlight for testing. Thanks.

**Comment by mssun** [comment] 2019-11-20 23:14
In TestFlight 0.8.0 (41), please take a look.

**Comment by ismail** [comment] 2019-11-21 20:24
> In TestFlight 0.8.0 (41), please take a look.

Just tested, clone & pull works just fine. Great work!

**Comment by mssun** [comment] 2019-11-23 00:12
Closed, 0.8.0 (41) has been published in App Store.

Feel free to reopen this or create a new one if there are more related issues.

**Closed by mssun** 2019-11-23 00:12 UTC
Labels: git, in TestFlight
