### ISSUE TITLE
Can't clone any repo using SSH

### ISSUE THREAD

**Issue by intelfx** [mssun/passforios#105] opened 2017-07-03 12:58 UTC
I'm running (jailbroken) iOS 10.2 on iPhone 5S, using Pass for iOS 0.2.7 from AppStore. There is a problem with setting up a Git repo for sync using SSH keys. I tried syncing with a self-hosted repo and GitHub — both yield a generic error when trying to clone (using a password with the self-hosted server does not work too).

After a successful key exchange and typing in the key passphrase (or the account password), the server logs say:

```
июл 03 15:56:44 server sshd[2698]: Connection closed by authenticating user operator 176.59.51.17 port 12868 [preauth]
```

Then the generic error appears and the connection is closed.

**Comment by yishilin14** [comment] 2017-07-03 13:18
About syncing GitHub repo, here goes one example of the ssh url: `ssh://git@gitlab.com/passforios-demo/demo.git`, and the username should be `git`. For more, please refer to our [wiki](https://github.com/mssun/passforios/wiki#ssh-url-example). I am able to clone from GitHub using my SSH key.

For self-hosted repo, there is another similar issue #95. I guess the problem is caused by some bug of the upstream library we are using. We will try our best to debug.

**Comment by intelfx** [comment] 2017-07-03 14:42
@yishilin14 OK, I've found the problem. You have to **both** say the username in the repo URL **and** fill the "username" field.

You may want to fix this.

**Comment by yishilin14** [comment] 2017-07-03 14:46
Are you able to clone both your self-hosted repo and Github repo now?

Both the username in the repo URL and the username field are required. We are already giving examples in our [Wiki](https://github.com/mssun/passforios/wiki/Building-Pass-for-iOS). We are thinking about adding a link to it in the repo setup.

**Comment by intelfx** [comment] 2017-07-03 14:52
Ah, OK, it wasn't actually obvious from the docs that you have to say username in both places... However, I don't see why you can't just extract the username from the repo URL.

**Comment by yishilin14** [comment] 2017-07-03 14:54
I will polish the working in the wiki. :-)
Extracting the username from the repo URL sounds doable, we will put it into our todo-list.

**Comment by yishilin14** [comment] 2017-07-22 11:23
I am closing this issue because it seems like the cloning worked for you.

We are providing more information about the git clone errors (e.g., wrong user name) in the coming release. I think the extra error messages complements the Wiki page.

**Closed by yishilin14** 2017-07-22 11:23 UTC
