### ISSUE TITLE
Multiple public GPG keys

### ISSUE THREAD

**Issue by goerz** [mssun/passforios#214] opened 2018-09-05 02:39 UTC
My pass setup uses two different gpg keypairs. On my laptop, I have both public keys, and one of the private keys. On iOS, I have both the public and the private key for the second one of the keypairs, but neither the public or the private key for the first keypair. I just realized this means that when I edit the database on iOS, I will not be able to decrypt it on the the laptop, because iOS doesn't have the first public key, and thus doesn't use it for encryption.

Could you add support for additional public gpg keys?

**Comment by yishilin14** [comment] 2018-09-05 05:04
Duplicate of #52.

We haven't got the time to implement this yet. This feature now has the highest priority in our enhancement todo list.

I am closing this one, and keep #52 open.

**Closed by yishilin14** 2018-09-05 05:04 UTC
