### ISSUE TITLE
Remembering PGP passphrase not working 

### ISSUE THREAD

**Issue by kkga** [mssun/passforios#256] opened 2019-03-23 11:00 UTC
I’ve set up 2 iOS devices with the PGP via iTunes file sharing.
The problem I have is one of them keeps asking me for the passphrase on each autofill and also every time I edit an entry in the app.
I’ve also tried copying the key via ASCII armor on that device and still having the same issue.
Can anyone help me figure out what’s the problem here? Thank you.

**Comment by yishilin14** [comment] 2019-03-25 06:15
Thanks for reporting. I will take a look.

**Comment by kkga** [comment] 2019-03-25 10:16
Is it possible that I somehow messed up the pgp encryption and encrypted them twice? 😅 I've been messing with the keys while trying to set up the password store, so I'm not sure if it's related to Passforios... `pass` cmd tool works fine though

**Comment by yishilin14** [comment] 2019-03-25 10:19
Are you able to encrypt/decrypt your pass entries after entering your passphrase manually?

**Comment by yishilin14** [comment] 2019-05-10 04:41
I am closing this issue because I am not able to reproduce it.

If you are still bothered by this, please feel free to reopen and provide more information. Thanks.

**Closed by yishilin14** 2019-05-10 04:41 UTC

**Comment by muellerj** [comment] 2019-06-14 13:31
I am experiencing the same problem. When I enter the credentials, I can decrypt all entries in my store. After for example deleting one of the the password seems to be „forgotten“ and I am prompted again. 

How can I provide additional information?

**Comment by muellerj** [comment] 2019-06-14 13:38
If it helps, I am able to decrypt entries, edit them and read them again. In between saving and viewing them, I have to re-enter my passphrase.

**Comment by yishilin14** [comment] 2019-06-14 16:17
@muellerj  "Deleting an entry wipes our the PGP passphrase"  is solved 0.6.0(17). 
If you are a TestFlight user, please try 0.6.0(17).
If you are not, save the passphrase again in order to "remember" it.

**Comment by muellerj** [comment] 2019-06-15 05:56
I am on 0.5.1 (30). How do I become a TestFlight user?

**Comment by yishilin14** [comment] 2019-06-15 06:12
If you want to join the iOS beta via TestFlight, drop an email to developer@passforios.mssun.me. Thank you.

**Comment by muellerj** [comment] 2019-06-15 09:31
I can confirm that the problem is fixed with 0.6.0. Thanks for the quick help!
