### ISSUE TITLE
https Clone does not work with gogs

### ISSUE THREAD

**Issue by johamha** [mssun/passforios#309] opened 2019-09-20 09:12 UTC
Cloneing the repo with https from a goos repo does not work. 
No error message no progress bar, just the password prompt pops up and then nothing. 
Pass for iOS 0.7.0 (15) from App Store

**Comment by mssun** [comment] 2019-09-20 17:12
Thanks! Can you send me an email `developer@passforios.mssun.me` to me so that I can invite you to our TestFlight?

**Comment by muellerj** [comment] 2019-09-23 07:09
I have a similar problem. With my standard password (> 30 chars), the clone would not work. No error message but no success either. When I change the password on the server to something trivial (e.g. “foo”), the clone works.

**Comment by mssun** [comment] 2019-09-23 07:12
@muellerj, you mean a long SSH password makes it not working?

**Comment by muellerj** [comment] 2019-09-23 09:05
Sorry if that was poorly written - I mean the https password used by `nginx` to secure the git repository. AFAIK, the meachanism is implemented via `HTTP_BASIC_AUTH`.

I did not check a connection via SSH.

**Comment by SrGMC** [comment] 2019-09-25 20:40
I have more details about the bug in Pass for iOS (from now on Pass). It also happens if you use SSH (with key) to clone a repository from a `gogs` server. Either it does nothing, or loads indefinitely. 

A workaround I found, is making the repository public temporarily, then cloning it with Pass and then making the repository private again. Then you can make changes in Pass, but unfortunately you can't push or pull to the repository, whether it's public or private.
But if you cloned a repository before Pass v0.7.0 (App Store version), push and pull will work just fine.

My setup also uses `nginx` as a reverse proxy. I don't know (mainly because `gogs` needs to be configured for HTTPS)  if the same happens when accessing `gogs` directly through the server's IP and default port (`gogs` default one is `3000`, ie. `https://192.168.0.100:3000`)

**Comment by muellerj** [comment] 2019-09-27 17:45
I can also reproduce the problem with `Gogs`.

I workaround here is also as follows:

1. Change the password of the user in question to something trivial ("foo")
2. Clone the repo using that short password (this works)
3. Change the user password back to its original state
4. Refresh passforios by pulling down in the list of passwords
5. This offers a prompt to update the password - enter the full password
6. The app now hangs, but after killing it manually the password seems to be stored and updates work.

@@mssun: If you are interested in a test environment to reproduce the problem, let me know. I can generate a test user for you on my server.

**Comment by mssun** [comment] 2019-11-24 05:09
Hi, I registered an account at https://try.gogs.io and set a 32 chars long password. The latest version v0.8.0 (41) works and can clone the private repo. Can you help me to verify this problem still exits in the latest release. Thanks.

**Comment by muellerj** [comment] 2019-11-24 09:07
Hi,

I can confirm that the current version works for my setup as well. Please consider my problem solved. 

Kind regards,
Jonas

**Comment by mssun** [comment] 2019-11-24 09:19
Thanks, I think this could be fixed by the recent update of libssh2. Thanks!

**Closed** 2019-11-24 09:19 UTC
