### ISSUE TITLE
[Feature Request] YubiKey 5Ci support

### ISSUE THREAD

**Issue by ibihim** [mssun/passforios#297] opened 2019-08-27 08:27 UTC
There is a new Yubikey with a lightning connection: yubikey 5ci. It would be amazing to use the private key stored on it.

Could the support be added?

**Comment by awehrfritz** [comment] 2019-08-28 14:44
This is a duplicate of #42

**Comment by yishilin14** [comment] 2019-09-02 15:47
This is a duplicate of #42. We do need help on this. :-)

**Closed by yishilin14** 2019-09-02 15:47 UTC
