### ISSUE TITLE
Error : The file couldn't  be saved using the specified text encoding

### ISSUE THREAD

**Issue by llann** [mssun/passforios#64] opened 2017-03-19 21:55 UTC
Hi,

When I added my PGP-secretkey (private and public one), I then write my password and then "save" and when I get back to the "Settings" and get this error message

"Error : The file couldn't  be saved using the specified text encoding".

**Comment by mssun** [comment] 2017-03-19 21:57
HI IIann, are you using ascii-armered key? For this case, you should check if all character is ascii.

**Comment by mssun** [comment] 2017-03-21 00:20
@llann Any update? Is everything OK right now?

**Comment by mssun** [comment] 2017-03-24 02:42
I'm closing this issue. Feel free to reopen it if you have further information. Thanks.

**Comment by llann** [comment] 2017-03-24 09:10
Sorry for the late answer.

Yes it's an ascii-armored key.

**Comment by yishilin14** [comment] 2017-03-28 17:27
Hi @llann . Without more information to reproduce, it is not possible for us to debug. 

I agree with mssun. My guessing is that the reason for you to see this message is **non-ascii characters** that you put there. It is possible that the way you got your keys from your PC to your phone changed the encoding (e.g., "--" to "—" in my experience). 

Example of "bad encoding"
- If you type non-ascii characters (e.g., any emoji), you shall see "The file couldn't be saved using the specified text encoding".

**Comment by yishilin14** [comment] 2017-04-03 17:20
Feel free to reopen it if you have further suggestions. Thanks.

**Closed by yishilin14** 2017-04-03 17:20 UTC
