### ISSUE TITLE
App crashes after adding ecdsa pgp key

### ISSUE THREAD

**Issue by iavael** [mssun/passforios#160] opened 2018-02-16 17:51 UTC
After adding ecdsa key app immideately crashes and then starts crashing on start.

**Comment by iavael** [comment] 2018-02-16 18:06
Here are crash reports:
* [key add crash](https://github.com/mssun/passforios/files/1732336/pass-2018-02-16-204724.ips.gz)
* [startup crash](https://github.com/mssun/passforios/files/1732326/pass-2018-02-16-204730.ips.gz)

**Comment by benjbellon** [comment] 2018-02-23 07:51
I am also receiving this error. Upon adding ecdsa keys, the app immediately crashes and then crashes immediately upon starting the app.

Crash reports:
[key add crash](https://github.com/mssun/passforios/files/1750807/pass-2018-02-22-234238.ips.gz)
[startup crash](https://github.com/mssun/passforios/files/1750809/pass-2018-02-22-234820.ips.gz)

**Comment by benjbellon** [comment] 2018-02-26 01:36
Looks like this is an error in ObjectivePGP. It appears that the library cannot successfully parse the ecdsa format. The apparent offending lines are in the various packet parsers:

Example:
https://github.com/krzyzanowskim/ObjectivePGP/blob/3ac2b25d279fb93b93c02907ff51cd49a071cea0/ObjectivePGP/Packets/PGPPublicKeyPacket.m#L139

I will file a bug with the project.

**Comment by benjbellon** [comment] 2018-02-26 01:52
@mssun and @iavael see the linked issue above. ecdsa is currently unsupported.

**Comment by yishilin14** [comment] 2018-03-01 17:05
@benjbellon Thank you.

**Comment by savyajha** [comment] 2018-08-12 06:48
Any RSA key types work fine. I'm using an RSA 4096 key with no problems. Ideally, I'd like to get on a better key type, but there's no real hurry at the moment.

**Comment by iavael** [comment] 2019-01-24 22:12
@benjbellon @yishilin14 
So maybe it's worth to check return value of readKeys for nil and show user a message instead of unconditionally crashing on start?
Ok, ecdsa is an unspported feature, bit it doesn't mean than program must crash.

**Comment by yishilin14** [comment] 2019-01-25 04:03
As far as I recall, ObjectivePGP crashes in this case. 

发自我的 iPhone

**Comment by iavael** [comment] 2019-01-25 17:46
@yishilin14 as far as I understand, this happens after passing nil to keyring.import
https://github.com/mssun/passforios/blob/1eba23e2a4a030828207d43065d7a63cb77a2450/passKit/Models/PasswordStore.swift#L241
because this function expects NSArray
https://github.com/krzyzanowskim/ObjectivePGP/blob/589ceead4332201440b81ccf082e52575e0514a8/ObjectivePGP/PGPKeyring.m#L41

**Comment by mssun** [comment] 2019-06-09 01:40
Hi all, thanks to @ZortacDev, we have changed to GopenPGP which may potentially resolves many existing PGP encryption algorithm issues. The latest version 0.6.0 (20) is in the TestFlight channel. Please report any issues related to the PGP encryption/decryption. Thanks.

**Comment by mssun** [comment] 2019-07-16 06:13
I'm closing this issue since we have released a new version in App Store to (to some extent) solve the PGP issues. Feel free to reopen it if you believe the issue is still valid.

**Closed by mssun** 2019-07-16 06:13 UTC
Labels: unsupported in dependent lib
