### ISSUE TITLE
Crash when importing RSA PGP-key and won't start after

### ISSUE THREAD

**Issue by simmel** [mssun/passforios#168] opened 2018-03-22 12:58 UTC
I started evaluating passforios for storing my password and I'm doing so with a newly generated PGP-key. I got it to work the first time I tried importing my PGP-key (but I think passforios crashed then too, but at least it started then).

After that I tried to use an EC key but that failed of course (I've since then read the issues related to this). But now everytime I import an PGP-key pass crashes and when I start it again it just closes down immediately. If I reinstall pass it works but crashes again if I try to add the RSA PGP-key.

Is it OK to paste the crashdump here or should I mail it?

**Comment by jsmestad** [comment] 2018-03-25 23:00
Having this same issue

**Comment by yishilin14** [comment] 2018-04-08 11:06
@simmel @jsmestad May I know how you guys generate your keys? I would like to generate keys by myself and do a fully test. In most cases, Pass crashes during adding PGP keys because keys are not supported by ObjectivePGP.

For example, as far as I know, EC keys are not supported by ObjectivePGP (https://github.com/krzyzanowskim/ObjectivePGP/issues/108).

**Comment by simmel** [comment] 2018-04-08 12:14
Hey!

I just used `gpg --gen-key`.

My keys are just temporary test keys (which has no value what so ever) 
so I'm emailing them to you.

I wonder if it has something to do with a key having multiple subkeys?

**Comment by krzyzanowskim** [comment] 2018-04-20 22:09
@simmel Can I take a look at the temporary test keys too?

**Comment by simmel** [comment] 2018-04-21 16:47
Nice try hackerman! ; P (I've sent them)

**Comment by mniak** [comment] 2018-08-10 11:32
I’m facing the same issue. Using ECDSA - curve 25519

**Comment by sliem** [comment] 2018-12-01 21:55
Same issue, using rsa2048.

**Comment by posix4e** [comment] 2019-01-12 06:50
I'm now having this issue with my newly generated keys.

**Comment by jacklund** [comment] 2019-02-10 04:54
I'm having the same issue, when importing using QR. My key also has subkeys, although I've tried just importing the master key as well. This is the sequence:

1. import private and public keys via QR
2. press "Save"
3. it asks if I want to give a passphrase (behavior doesn't seem to change whether I say yes or no here)
4. I say no, and it crashes.

After, I can't start it up again without deleting the app and reinstalling

**Comment by jacklund** [comment] 2019-02-10 05:12
Some more information: I tried cutting and pasting my keys into the dialog boxes, but when I hit save, it told me there was an error importing the keys. Just to verify, I took the same keys and tried to import them into a new GPG keyring, and they imported just fine. 

Is it possible that it doesn't support keys with subkeys?

**Comment by kraem** [comment] 2019-03-30 18:39
I'm experiencing the same behaviour with a 4096 bit key generated with ```gpg --gen-key --full-generate-key´´´
No subkeys though.

**Comment by mssun** [comment] 2019-06-09 01:41
Hi all, thanks to @ZortacDev, we have changed to [GopenPGP](https://github.com/ProtonMail/gopenpgp) which may potentially resolves many existing PGP encryption algorithm issues. The latest version 0.6.0 (20) is in the TestFlight channel. Please report any issues related to the PGP encryption/decryption. Thanks.

**Comment by mssun** [comment] 2019-07-16 06:21
I'm closing this issue since we have released a new version in App Store to (to some extent) solve the PGP issues. Feel free to reopen it if you believe the issue is still valid.

**Closed by mssun** 2019-07-16 06:21 UTC
Labels: pgp
