### ISSUE TITLE
Support for multiple password repos

### ISSUE THREAD

**Issue by samdmarshall** [mssun/passforios#139] opened 2017-10-26 19:27 UTC
I have a personal password repo and a separate one on my work computer. Having the app support being able to have multiple password "vaults", would be super useful.

**Comment by yishilin14** [comment] 2017-10-28 12:19
Duplicate of #139.

**Closed** 2017-10-28 12:21 UTC
Labels: duplicate

**Comment by samdmarshall** [comment] 2017-10-28 14:17
whoops, sorry about that.
