### ISSUE TITLE
Cannot clone Google Cloud repositories with "@" in username

### ISSUE THREAD

**Issue by dongcarl** [mssun/passforios#270] opened 2019-05-26 17:28 UTC
Google cloud repositories look something like this:
```
ssh://<accountname>@gmail.com@source.developers.google.com:2022/p/<projname>/r/<reponame>
```

When I try to set up a git server with that as the url and "<accountname>@gmail.com" as the username, there's a parsing error that believes the url and the username doesn't match.

I'm going to guess that `passforios` parses the username as the string up to the first `@` whereas it's supposed to be the string up to the last `@`.

**Comment by SimplyDanny** [comment] 2019-05-26 19:29
As of [section 3.1 in RFC 1738](https://tools.ietf.org/html/rfc1738#section-3.1) `@` is not allowed in the user name. So you may escape the first `@` using `%40`.

**Comment by dongcarl** [comment] 2019-05-27 19:01
@SimplyDanny Thanks!

Here's what I tried:
```
URL: ssh://<accountname>%40gmail.com@source.developers.google.com:2022/p/<projname>/r/<reponame>
Username: <accountname>@gmail.com
```
Result: "Underlying error: failed to start SSH session: Unable to exchange encryption keys"

```
URL: ssh://<accountname>%40gmail.com@source.developers.google.com:2022/p/<projname>/r/<reponame>
Username: <accountname>%40gmail.com
```
Result: "Please check the entered username and the username in the Git repository URL. They should match."

```
URL: ssh://<accountname>@gmail.com@source.developers.google.com:2022/p/<projname>/r/<reponame>
Username: <accountname>%40gmail.com
```
Result: "Please check the entered username and the username in the Git repository URL. They should match."

```
URL: ssh://<accountname>@gmail.com%40source.developers.google.com:2022/p/<projname>/r/<reponame>
Username: <accountname>
```
Result: "Underlying error: malformed URL"

**Comment by mssun** [comment] 2019-05-28 06:09
Hi @dongcarl, I think the first one should be correct. The cause of the result could be an unsupported key algorithm.

**Comment by mssun** [comment] 2019-06-09 04:23
The first one should be correct. I can confirm this issue, but my error message is "failed to start SSH session: Failed getting banner"

**Comment by mssun** [comment] 2019-11-25 06:16
Hi all, because of the update of libgit2/libssh2/openssl, I found that we can clone repos from Google Cloud. I'm using the following format and ED25519 key:

```
URL: ssh://<accountname>%40gmail.com@source.developers.google.com:2022/p/<projname>/r/<reponame>
Username: <accountname>@gmail.com
```

**Comment by mssun** [comment] 2019-11-25 07:05
I'm closing this issue. If this is still a problem, please feel free to reopen it. Thanks.

**Closed** 2019-11-25 07:04 UTC
Labels: bug
