### ISSUE TITLE
Cannot view any stored pass item after setup

### ISSUE THREAD

**Issue by hyiltiz** [mssun/passforios#456] opened 2021-01-31 08:37 UTC
## Tested environments

- the beta version `pass for iOS 0.12.0 (8)` from testflight on ` iOS 14.4` (has this issue)
- the stable version `pass for iOS 0.11.0 (11)` from App Store on ` iOS 14.4` (has this issue)
- `iOS 11.4 running Pass for iOS 0.9.0 (21)` (works without this issue)

## Steps to reproduce:
1. Set up a remote `https` git repo at gitlab via username and password (id_rsa 4096 key and id_ed25519 keys don't seem to be supported... but that is irrelevant to this). 
2. Also exported the gpg keys via local server URL (using `ruby -run -e httpd . -p 8080` and then `http://<local ip>:8080/a.asc` etc.). The import seemed fine, except it warned me not to use http but use https instead. 
3. Then I clicked on one pass item in the Passwords menu.  It asked for the PGP secret key Passphrase. 
4. I filled in the password correctly (I tried 20+ times, even via a bluetooth keyboard); the same password unlocks my gpg on my computer fine). 

## Result
However, once I finish inserting my password and click OK, I get:
```
Cannot show password
gopengp: unable to add locked key to a keyring
```

## Expected results:
The item opens, and shows the item view, where I could copy or show the password.

## Things I have tried to fix/rule out:
- Guessing it may have been talking about iOS keychain, I checked my keychain. It is synced fine with iCloud, and works fine.
- Tried several times after deleting the GPG key and several ways to export the gpg key (via key id, or the email etc.). 
- Also tried importing via iTunes (dropped the keys into the Pass Beta app then clicked iTunes import which showed a prompt saying "success"). 
- Tried deleting the app (along with its data) and completely setting up afresh.

None of those worked. Not sure what went wrong here. 

Let me know what more info I can provide to help debug or resolve this issue with better documentation.

Not sure if it is relevant, but I was using an old `iOS 11.4` running `Pass for iOS 0.9.0 (21)` before which worked (and still works) fine; I just migrated (via backing up to iTunes, ehm, it is called Music now and works directly from within Finder) from that to iOS 14.4.

**Comment by meeb** [comment] 2021-02-01 08:46
I'm having this exact issue with the same setup, manually imported GPG keys, can't unlock them as I get the same `unable to add locked key to a keyring` error. Using `pass for iOS 0.11.0` on `iOS 14.3`. As with the OP, this error occurred after upgrading from `0.9.0`. I am also positive the GPG passphrase is correct.

**Comment by hyiltiz** [comment] 2021-02-03 05:17
@mssun I can test out a few previous versions if you could make them available for download somewhere (or if you can push it via TestFlight to me).

**Comment by hyiltiz** [comment] 2021-02-04 19:27
From within testflight, there were a dozen versions available in each of the 0.10.0, 0.11.0 and 0.12.0 branches. I tried bisecting those, and found:

- `0.11.0 (10)` and later have the same issue described above;
- `0.10.0 (53) - 0.11.0 (8)` shows a different error prompt, still leaving the user unable to access the decrypted content. The prompt for these versions say: `gopengog: key is not locked`
- versions prior to `0.10.0 (53)` were not available in Testflight anymore.
- `0.9.0 (21)` installed on an old device running iOS 11.4 works without this (or any) issue

**Comment by hyiltiz** [comment] 2021-02-04 19:43
The issue seems relevant to #339. I successfully created two items from within passforios: `test` and `test-asc` with randomly generated passwords where `test` had `Encrypt in ASCII-Armored` disabled and `test-asc` with it enabled. Opening either of them in passforios fails with the same issue as reported here. I synced these two items, and pulled them into Debian, and did `gpg -d test.gpg` and `gpg -d test-asc.gpg`. Both of them decrypt successfully in Debian.

**Comment by hyiltiz** [comment] 2021-02-07 19:45
Can anyone build 84b1c07f6418779951028abf802d59c6b417f2e2^ for me? 84b1c07f6418779951028abf802d59c6b417f2e2 seems to be the commit that introduced a new gopenpgp library, and I wonder if this is the version between 0.9 and 0.10 that introduced this issue. We could then find out if it is a gopengpg issue, or can be fixed here by changing a few API calls.

**Comment by hyiltiz** [comment] 2021-02-07 20:15
The error is coming from gopenpgp:keyring.go:AddKey() function [1], which called gopenpgp:key.go:IsUnlocked() function. Upon closer inspection of this function, the error message I got and the subkeys attached to my key, it seems the error is coming from the following block of code [2]:
```{go}
	for _, sub := range key.entity.Subkeys {
		if sub.PrivateKey != nil && sub.PrivateKey.Encrypted {
			return false, nil
		}
	}
```
So, `IsUnlocked` seems to return `false` without any error message if any of the subkeys has an encrypted private key. So ultimately, `IsUnlocked` seems to somehow fail to decrypt the private key even though the password provided through `passforios` is typed correctly. Is it possible that the function calls to `gopengpg` from within `passforios` is not correctly specifying some parameter, such as whether the private key is ASCII armored, or that the stored encrypted password items are ASCII armored? As I explained earlier, I have both ASCII armored and binary encrypted password items, and both have the same issue.

[1] https://github.com/ProtonMail/gopenpgp/blob/d0daa53ca63a67fde26c9a51c3dfa0caa32f9ea6/crypto/keyring.go#L44
[2] https://github.com/ProtonMail/gopenpgp/blob/d0daa53ca63a67fde26c9a51c3dfa0caa32f9ea6/crypto/key.go#L284

**Comment by mssun** [comment] 2021-02-07 22:13
Hi @hyiltiz, thank you so much for this detailed description.

How did you generate your key? Let me reproduce your issue first.

**Comment by hyiltiz** [comment] 2021-02-07 23:34
I cannot recall exactly the commands used to generate the keys, but I just tested the following which should simulate my setup:


<details><summary>bash commands to reproduce the keys setup</summary>

```{bash}
$ gpg --full-gen-key --expert
gpg (GnuPG) 2.2.20; Copyright (C) 2020 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
   (7) DSA (set your own capabilities)
   (8) RSA (set your own capabilities)
   (9) ECC and ECC
  (10) ECC (sign only)
  (11) ECC (set your own capabilities)
  (13) Existing key
  (14) Existing key from card
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (3072) 4096
Requested keysize is 4096 bits
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want for the subkey? (3072) 4096
Requested keysize is 4096 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 2y
Key expires at Tue 07 Feb 2023 06:19:47 PM EST
Is this correct? (y/N) y

GnuPG needs to construct a user ID to identify your key.

Real name: test-passforios
Email address: test-passforios@example.com
Comment:
You selected this USER-ID:
    "test-passforios <test-passforios@example.com>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? C
Comment: Some comment, actually
You selected this USER-ID:
    "test-passforios (Some comment, actually) <test-passforios@example.com>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: key 916C280D626B53BB marked as ultimately trusted
gpg: revocation certificate stored as '/home/hyiltiz/.gnupg/openpgp-revocs.d/135775D14563B94978EC8531916C280D626B53BB.rev'
public and secret key created and signed.

pub   rsa4096/916C280D626B53BB 2021-02-07 [SC] [expires: 2023-02-07]
      135775D14563B94978EC8531916C280D626B53BB
uid                            test-passforios (Some comment, actually) <test-passforios@example.com>
sub   rsa4096/D818E26B4EAF5DAE 2021-02-07 [E] [expires: 2023-02-07]

$ # now let's add a key that is used for authentication only
$ gpg --edit-key --expert test-passforios
gpg (GnuPG) 2.2.20; Copyright (C) 2020 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Secret key is available.

sec  rsa4096/916C280D626B53BB
     created: 2021-02-07  expires: 2023-02-07  usage: SC  
     trust: ultimate      validity: ultimate
ssb  rsa4096/D818E26B4EAF5DAE
     created: 2021-02-07  expires: 2023-02-07  usage: E   
[ultimate] (1). test-passforios (Some comment, actually) <test-passforios@example.com>

gpg> addkey
Please select what kind of key you want:
   (3) DSA (sign only)
   (4) RSA (sign only)
   (5) Elgamal (encrypt only)
   (6) RSA (encrypt only)
   (7) DSA (set your own capabilities)
   (8) RSA (set your own capabilities)
  (10) ECC (sign only)
  (11) ECC (set your own capabilities)
  (12) ECC (encrypt only)
  (13) Existing key
  (14) Existing key from card
Your selection? 8

Possible actions for a RSA key: Sign Encrypt Authenticate 
Current allowed actions: Sign Encrypt 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? A

Possible actions for a RSA key: Sign Encrypt Authenticate 
Current allowed actions: Sign Encrypt Authenticate 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? S

Possible actions for a RSA key: Sign Encrypt Authenticate 
Current allowed actions: Encrypt Authenticate 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? E

Possible actions for a RSA key: Sign Encrypt Authenticate 
Current allowed actions: Authenticate 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? Q
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (3072) 4096
Requested keysize is 4096 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 3y
Key expires at Wed 07 Feb 2024 06:28:33 PM EST
Is this correct? (y/N) y
Really create? (y/N) y
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.

sec  rsa4096/916C280D626B53BB
     created: 2021-02-07  expires: 2023-02-07  usage: SC
     trust: ultimate      validity: ultimate
ssb  rsa4096/D818E26B4EAF5DAE
     created: 2021-02-07  expires: 2023-02-07  usage: E
ssb  rsa4096/7A0F8F755F1B7CDD
     created: 2021-02-07  expires: 2024-02-07  usage: A
[ultimate] (1). test-passforios (Some comment, actually) <test-passforios@example.com>

gpg> save

$ # we are done!

$ gpg --list-secret-keys test-passforios
sec   rsa4096/916C280D626B53BB 2021-02-07 [SC] [expires: 2023-02-07]
      135775D14563B94978EC8531916C280D626B53BB
uid                 [ultimate] test-passforios (Some comment, actually) <test-passforios@example.com>
ssb   rsa4096/D818E26B4EAF5DAE 2021-02-07 [E] [expires: 2023-02-07]
ssb   rsa4096/7A0F8F755F1B7CDD 2021-02-07 [A] [expires: 2024-02-07]
```
</details>
<summary>

The created keys are attached, and the password for the keys is `password2021`. 
[password2021.zip](https://github.com/mssun/passforios/files/5940401/password2021.zip)

DISCLAIMER: I have yet to test if these keys also have the same behavior... But their `--list-keys` entries looks similar to my setup and as far as I can remember, these keys are generated in the same way.

**Comment by mssun** [comment] 2021-02-07 23:36
Thank you. Let me have a try.

**Comment by hyiltiz** [comment] 2021-02-07 23:45
My key was signed by a few people. I wonder if that is relevant...

**Comment by mssun** [comment] 2021-02-07 23:52
You said "EDIT: I just re-encrypted all my items, synced to my phone and tested out pass beta with the newly generated key following the above procedure. The issue disappeared..."

This is wired...

**Comment by hyiltiz** [comment] 2021-02-07 23:53
Yeah, I now re-encrypted back with `pass init hyiltiz@gmail.com` so I could test out my original keys. The original keys has the issue reported here. So simply re-encrypting to something else then back doesn't solve anything... This is so bizarre.

**Comment by mssun** [comment] 2021-02-07 23:57
Can you try your original key again? There's definitely something wrong here.

**Comment by hyiltiz** [comment] 2021-02-08 00:04
> Yeah, I now re-encrypted back with `pass init hyiltiz@gmail.com` so I could test out my original keys. The original keys has the issue reported here. So simply re-encrypting to something else then back doesn't solve anything... This is so bizarre.

I tried my original key above. So far, we know:
1. password-store was initialized to my original keys; doesn't work;
2. password-store was initialized to newly generated keys (that /mostly/ follows the same procedure to generate the keys); works
3. password-store was initialized back to my original keys: doesn't work.

Apparently, something is special with my original keys. My original keys and the newly generated keys has the same output for ` gpg --with-colons --import-options show-only --import`
```
$ cat test-passforios.asc | gpg --with-colons --import-options show-only --import
sec:u:4096:1:916C280D626B53BB:1612740024:1675812024::u:::scESCA::::::23::0:
fpr:::::::::135775D14563B94978EC8531916C280D626B53BB:
grp:::::::::3993A2BE9B8DE63DDC21BDDABAAD91A150C1F94C:
uid:u::::1612740024::BC20BDEF17BB4912707B9BA180EA62FE232F615F::test-passforios (Some comment, actually) <test-passforios@example.com>::::::::::0:
ssb:u:4096:1:D818E26B4EAF5DAE:1612740024:1675812024:::::e::::::23:
fpr:::::::::469D5C821A0220DFFC62305CD818E26B4EAF5DAE:
grp:::::::::19F28C6B43BB5675FE33DC50115C6C499F851E07:
ssb:u:4096:1:7A0F8F755F1B7CDD:1612740475:1707348475:::::a::::::23:
fpr:::::::::C0C37272C21C9F24353F7DFB7A0F8F755F1B7CDD:
grp:::::::::E772DD73921F202E519A3B165A3AC3C873132711:
```

but they seem to differ quite a bit when I dumped more detail with `gpg --list-packets`. I am hesitant if publishing the contents of `gpg --list-packets` is a safe practice, but the newly generated key has:
```
$ cat test-passforios.asc | gpg --list-packets 
# off=0 ctb=95 tag=5 hlen=3 plen=1862
:secret key packet:
        version 4, algo 1, created 1612740024, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        iter+salt S2K, algo: 7, SHA1 protection, hash: 2, salt: 3619DB299A53B16F
        protect count: 65011712 (255)
        protect IV:  4d 50 a6 d5 fe e3 cc 8c 4e ea 2c e5 4e b8 e8 35
        skey[2]: [v4 protected]
        keyid: 916C280D626B53BB
# off=1865 ctb=b4 tag=13 hlen=2 plen=70
:user ID packet: "test-passforios (Some comment, actually) <test-passforios@example.com>"
# off=1937 ctb=89 tag=2 hlen=3 plen=596
:signature packet: algo 1, keyid 916C280D626B53BB
        version 4, created 1612740024, md5len 0, sigclass 0x13
        digest algo 10, begin of digest a2 00
        hashed subpkt 33 len 21 (issuer fpr v4 135775D14563B94978EC8531916C280D626B53BB)
        hashed subpkt 2 len 4 (sig created 2021-02-07)
        hashed subpkt 27 len 1 (key flags: 03)
        hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
        hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 10 9 8 11 2)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (keyserver preferences: 80)
        subpkt 16 len 8 (issuer key ID 916C280D626B53BB)
        data: [4094 bits]
# off=2536 ctb=9d tag=7 hlen=3 plen=1862
:secret sub key packet:
        version 4, algo 1, created 1612740024, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        iter+salt S2K, algo: 7, SHA1 protection, hash: 2, salt: F62B1450ED573A82
        protect count: 65011712 (255)
        protect IV:  22 61 be a7 c6 bb 5a 1f c9 57 3b 1a 0d 2e 58 e4
        skey[2]: [v4 protected]
        keyid: D818E26B4EAF5DAE
# off=4401 ctb=89 tag=2 hlen=3 plen=572
:signature packet: algo 1, keyid 916C280D626B53BB
        version 4, created 1612740024, md5len 0, sigclass 0x18
        digest algo 10, begin of digest 10 76
        hashed subpkt 33 len 21 (issuer fpr v4 135775D14563B94978EC8531916C280D626B53BB)
        hashed subpkt 2 len 4 (sig created 2021-02-07)
        hashed subpkt 27 len 1 (key flags: 0C)
        hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
        subpkt 16 len 8 (issuer key ID 916C280D626B53BB)
        data: [4095 bits]
# off=4976 ctb=9d tag=7 hlen=3 plen=1862
:secret sub key packet:
        version 4, algo 1, created 1612740475, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        iter+salt S2K, algo: 7, SHA1 protection, hash: 2, salt: ADD7A1949CC2E05D
        protect count: 65011712 (255)
        protect IV:  60 8d f8 0a 31 85 e2 ef 4a 8f 00 35 c1 16 3c 21
        skey[2]: [v4 protected]
        keyid: 7A0F8F755F1B7CDD
# off=6841 ctb=89 tag=2 hlen=3 plen=572
:signature packet: algo 1, keyid 916C280D626B53BB
        version 4, created 1612740475, md5len 0, sigclass 0x18
        digest algo 10, begin of digest 31 e4
        hashed subpkt 33 len 21 (issuer fpr v4 135775D14563B94978EC8531916C280D626B53BB)
        hashed subpkt 2 len 4 (sig created 2021-02-07)
        hashed subpkt 27 len 1 (key flags: 20)
        hashed subpkt 9 len 4 (key expires after 3y0d0h0m)
        subpkt 16 len 8 (issuer key ID 916C280D626B53BB)
        data: [4095 bits]
```

**Comment by hyiltiz** [comment] 2021-02-08 00:09
I also tried only exporting my encryption subkey (from the original one) with `gpg -a --export-secret-subkeys` along with the pubkey with `gpg -a --export` using the encryption subkey id. They imported successfully, but gave the same error as reported in OP.

**Comment by mssun** [comment] 2021-02-08 00:20
Yes, @hyiltiz. Thank you so much! This is very helpful.

**Comment by hyiltiz** [comment] 2021-02-08 00:40
@meeb can you tell us some more about your key setup, aka how your keys are generated? As you can see above, I failed to come up with a procedure that could exhibit the same issue with a newly generated key pair. Maybe by comparing with your setup, we could have a lead?

**Comment by meeb** [comment] 2021-02-08 04:41
Ah you might be on to something. The GPG key I was using with on my phone is indeed a subkey of a parent key. The keys, both root/parent key and subkeys were generated as usual on my Linux desktop with gpg2 and just the key used for the password store was exported to the phone. There appears to be no issue with the keys themselves and they work everywhere else.

**Comment by pgrupp** [comment] 2021-02-08 20:07
Hi folks, I've had the same issue. But somehow it seems to be fixed now. Me stupid, I was exporting the secret key with the `--export-secret-keys` flag instead of the `--export-secret-subkeys`. That might have been the/a reason for the issue.
Additionally what might have caused the issue as well is that I've recently updated my subkeys and extended their expiration time. What I was doing is delete the whole keyset from the machine and import an old export of the master key and all subkeys (private+public) into GPG. When checking the key after that, the expiry was already extended again, I suppose upon import GPG automatically refreshes it from the keyservers, so I'm not sure if that actually had an effect in the end. Anyways when doing the export 
```
gpg --armor --export [key-id] > gpg_key.pub
gpg --armor --export-secret-subkeys [key-id] > gpg_key
```
then and importing into the App using the "via iTunes" option it just worked... 🤔 
My head hurts now 😄 I'm not sure, if this helps you guys further debug the issue, but I thought I'd throw it in for your considerations :) 

Also I usually use the same key on a Yubikey smartcard, so i usually need to remove the private key reference to the smartcard from the local GPG using the subkeys' keygrips. And reimport the fully local private keys again. So if you do something similarly crazy, you'll need to make sure that the smartcard is not being referenced at all 😜 But that's probably just my crazy setup 😄

**Comment by hyiltiz** [comment] 2021-02-09 18:36
Thx @pgrupp! I did try exporting only the secret subkeys (details above) but that didn't work. But it is most likely very relevant to the subkeys as the gopenpgp code snippet giving this error just deals with subkeys.

**Comment by mssun** [comment] 2021-02-10 05:13
We have a test case for RSA4096 secret subkey:
https://github.com/mssun/passforios/blob/1454693308b6fb73519aaefc32f6bbb3eecc5821/passKitTests/Testbase/TestPGPKeys.swift#L41-L46

Can anyone provide step by step commands to generate such key which break the gopenpgp library.

**Comment by hyiltiz** [comment] 2021-02-11 05:05
Would getting the key signed by someone else be relevant? Suppose a few people signed the main key and/or (some of) the subkeys in a key signing party.

**Comment by kkonopko** [comment] 2021-02-26 11:54
I have exactly the same issue as @hyiltiz, same story about past versions etc.  Similar setup as well: 4096 encryption and authentication sub-keys (the latter I use for SSH).  I don't have any of my keys signed, but I have my own trust set on them (ultimate) which seemed to be required by `pass` (or something else I can't remember now).

**Comment by kkonopko** [comment] 2021-02-26 11:55
> Thx @pgrupp! I did try exporting only the secret subkeys (details above) but that didn't work. But it is most likely very relevant to the subkeys as the gopenpgp code snippet giving this error just deals with subkeys.

Same here.

**Comment by misaka18931** [comment] 2021-02-27 12:57
> Thx @pgrupp! I did try exporting only the secret subkeys (details above) but that didn't work. But it is most likely very relevant to the subkeys as the gopenpgp code snippet giving this error just deals with subkeys.

In my case, neither the ```--export-secret-subkeys``` nor ```--export-secret-keys``` option works.  
The key files can be successfully imported with no exceptions, but when I try to decrypt the passwords, it says "PGP public key may be expired or incompatible with the private key."

environment: iPadOS 14.4, pass for ios 0.11.0(11)
gpg keypair setup: 4096bit RSA key, ASCII-Armored, RSA and RSA

**Comment by hyiltiz** [comment] 2021-02-27 20:35
Oh `PGP public key may be expired or incompatible with the private key.` is a new error message though; Would be very interested to find out if the root casuse is the same @misaka18931 Can you tell us mroe about your key set up?

@kkonopko I also use (or tried to use, really) one of the subkeys for SSH auth. I never got it working and don't recall what I did to do so. Could you give us a set of steps to produce a key with a subkey that supports SSH auth (which hopefully works with SSH)? We can test if we can reproduce the issue with that. We are having a re-producability problem here. The issue is very real, and once we can get test key that can reproduce it, we'll be able to hunt it down.

**Comment by kkonopko** [comment] 2021-03-01 06:32
@hyiltiz I think I pretty much followed this: https://opensource.com/article/19/4/gpg-subkeys-ssh-multiples

**Comment by misaka18931** [comment] 2021-03-01 11:42
@hyiltiz I used ```gpg --full-gen-key``` to generate my keys, and I went through most of the options with default value.   
I selected the ```(1) RSA and RSA (default)``` option, then chose the 4096 bits key and never expire.
Then I used ```gpg --output revoke.asc --gen-revoke``` as the gpg man page recommands to do that.
I used ```gpg --export-keys -a --output public.asc``` and ```gpg --export-secret-keys -a --output private.asc``` to export the key pairs.
```gpg --list-keys``` outputs this:
```
pub   rsa4096 2021-02-27 [SC]
      06A.................................
uid           [ultimate] .......................Key Identifier...........................
sub   rsa4096 2021-02-27 [E]
```
gpg --list-secret-keys``` outputs this:
```
sec   rsa4096 2021-02-27 [SC]
      ...........Key Hash.................
uid           [ultimate] ...........key ID...................
ssb   rsa4096 2021-02-27 [E]
```

**Comment by misaka18931** [comment] 2021-03-01 13:49
Update: That behavior is likely to be an issue of pass itself:
Previously whenever I try another gpg keypair setups, I change the keys by ```pass init``` with ```-p``` flag, but today I removed the entire ```.password-store``` directory and re generate the passwords, and now it works fine for me.
Thanks anyway.

**Comment by telnoratti** [comment] 2021-03-31 02:22
I got this error and tried both `--export-secret-subkeys` and `--export-secret-keys` with no luck. When editing the key I noticed I had both a revoked subkey and an expired subkey. I deleted the keys, exported the key again, then imported into passforios, and was able to decrypt passwords after that. They keys don't show up with `--list-keys` and only were visible when I was in the `--edit-key` prompt and used the `list` command.

I restored my keys from a backup after that. I'm pretty sure I don't have anything encrypted to those subkeys and they were just used for testing, but I could see how these keys might have tripped the lines of code in gopengpg that @hyiltiz identified.

**Comment by hyiltiz** [comment] 2021-07-05 18:06
@telnoratti  I think you may have pinpointed the issue at hand here. Most long time gpg users will have a few expired/revoked subkeys hanging around, and keeping them around is the recommended practice (by GPG official site). @mssun do you think you can reproduce the steps @telnoratti described? If so, we can either patch gopengpg ourselves within passforios or just submit the patch to them. Should be as simple as checking a subkey property to see if it is valid before using it.

**Comment by hyiltiz** [comment] 2021-09-30 07:17
@telnoratti I tried what you suggested but without luck. Here is what I did:
- `gpg --edit-key MY_KEY_ID`
- `list` to show the keys
- `1` to select a key
- `expire` to edit the expiration dates of all the subkeys  to `never`
- `list` now shows
```
sec  rsa4096/XXXXXXXXXXXXXXXX
     created: 2016-07-24  expires: 2022-09-28  usage: SC
     trust: ultimate      validity: ultimate
ssb  rsa4096/XXXXXXXXXXXXXXXX
     created: 2016-07-24  expires: never       usage: E
sub  rsa4096/XXXXXXXXXXXXXXXX
     created: 2018-07-10  expires: never       usage: A
[ultimate] (1). Hormet Yiltiz <hyiltiz@gmail.com>
```
Originally, the `ssb` encryption subkey and the `sub` auth subkey had expiration dates (though not yet expired). I noticed that it is common to have a `sec` key for Signature `SC` followed by an `ssb` key for Encryption `E`. Maybe the additional Auth subkey is messing it up?

**Closed** 2021-09-30 17:55 UTC
